builds:
  - binary: humio
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: humio
    name: cli-go


brew:
  github:
    owner: goreleaser
    name: homebrew-tap
  folder: Formula
  homepage:  http://goreleaser.github.io
  description: Deliver Go binaries as fast and easily as possible
  test: |
    system "echo DONE"


archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Linux
  files:
    - LICENSE.md
    - CHANGELOG.md
  format_overrides:
    - goos: windows
      format: zip
